apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: financial-report-reports-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: financial-report-logs-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi 