apiVersion: v1
kind: Secret
metadata:
  name: financial-report-secrets
  namespace: marketplace
type: Opaque
data:
  API_TOKEN: YmRkM2Q1MWMtZGU1MC00Y2U1LWFhYWUtYWRlOTNmNjY4MTA5
  APPLICATION_ID: OTg4MDI0MjgyOA==
  SELLER_ID: WVNLVzk3NDQ2MDE2NTg5Mjc1 